// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {main} from '../models';

export function AddTodo(arg1:time.Time,arg2:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateMarkdownFile(arg1:string,arg2:string):Promise<void>;

export function DateToTimestamp(arg1:string,arg2:boolean):Promise<number>;

export function DecodeString(arg1:string,arg2:string):Promise<string>;

export function EncodeString(arg1:string,arg2:string):Promise<string>;

export function FormatJSON(arg1:string,arg2:boolean):Promise<string>;

export function GetTodos(arg1:time.Time):Promise<Array<main.Todo>>;

export function Greet(arg1:string):Promise<string>;

export function HashString(arg1:string,arg2:string):Promise<string>;

export function ListMarkdownFiles(arg1:string):Promise<Array<string>>;

export function ReadMarkdownFile(arg1:string):Promise<string>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function SaveMarkdownFile(arg1:string,arg2:string):Promise<void>;

export function TimestampToDate(arg1:number,arg2:boolean):Promise<string>;

export function UpdateTodo(arg1:number,arg2:boolean):Promise<void>;
