// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1, arg2) {
  return window['go']['main']['App']['AddTodo'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['CreateMarkdownFile'](arg1, arg2);
}

export function DateToTimestamp(arg1, arg2) {
  return window['go']['main']['App']['DateToTimestamp'](arg1, arg2);
}

export function DecodeString(arg1, arg2) {
  return window['go']['main']['App']['DecodeString'](arg1, arg2);
}

export function EncodeString(arg1, arg2) {
  return window['go']['main']['App']['EncodeString'](arg1, arg2);
}

export function FormatJSON(arg1, arg2) {
  return window['go']['main']['App']['FormatJSON'](arg1, arg2);
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetTodos(arg1) {
  return window['go']['main']['App']['GetTodos'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HashString(arg1, arg2) {
  return window['go']['main']['App']['HashString'](arg1, arg2);
}

export function ListMarkdownFiles(arg1) {
  return window['go']['main']['App']['ListMarkdownFiles'](arg1);
}

export function ReadMarkdownFile(arg1) {
  return window['go']['main']['App']['ReadMarkdownFile'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2);
}

export function SaveMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['SaveMarkdownFile'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetCurrentDirectory(arg1) {
  return window['go']['main']['App']['SetCurrentDirectory'](arg1);
}

export function TimestampToDate(arg1, arg2) {
  return window['go']['main']['App']['TimestampToDate'](arg1, arg2);
}

export function UpdateTodo(arg1, arg2) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2);
}
